version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: arkosp@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 80:80
